refactor(restructure_wsl_dropbox_path): Consolidate cd to dropbox code - Consolidate cdwin alias into alias variable - Remove other functions to deprecated

diff --git a/dotfiles/bashrc b/dotfiles/bashrc
--- a/dotfiles/bashrc
+++ b/dotfiles/bashrc
@@ -57,8 +57,13 @@ MY_SHELL_ALIASES=(
   "ll=ls -alF"
   "la=ls -A"
   "l=ls -CF"
+  # --- Programming language aliases ---
   "R=R --no-save"
+
+  # --- WSL/WINDOWS related ---
+  "cdwin=cd \"\$DROPBOX_PATH\"" # Escape the quotes and the $ to prevent expansion and quote when evaluated
   "explorer=explorer.exe ."
+
   # --- Git aliases ---
   "ga=git add"
   "gb=git branch"
@@ -92,14 +97,71 @@ done
 log_info "Aliases configured successfully"
 
 # Set up environment variables and paths
-setup_environment
+log_info "Setting up environment..."
+# Path configurations
+#ADDITIONAL_PATHS=(
+#    "~/node-v22.5.1-linux-x64/bin"
+#)
+# Add additional paths
+#for path in "${ADDITIONAL_PATHS[@]}"; do
+#    eval "path_expanded=$path"
+#    [[ -d "$path_expanded" ]] && PATH="$PATH:$path_expanded"
+#done
+
+# Environment variables
+ENV_VARS=(
+   "BROWSER=/mnt/c/Program Files (x86)/BraveSoftware/Brave-Browser/Application/brave.exe"
+   "GIT_EDITOR=nvim"
+   "R_HOME=/usr/local/bin/R"
+   "R_LIBS_USER=/opt/R/library/"
+)
+
+# Set environment variables
+for var in "${ENV_VARS[@]}"; do
+  export "$var"
+done
+
+log_info "Environment variables configured..."
 
 # Set vi mode
 set -o vi
 
 # Set up Windows environment if in WSL
 if [[ -n "$WSL_DISTRO_NAME" ]]; then
-  setup_windows_environment
+  #setup_windows_environment
+    windows_user=$(cmd.exe /C "echo %USERNAME%" 2>/dev/null | tr -d '\r\n')
+    if [[ -z "$windows_user" ]]; then
+      log_error "Error: Unable to retrieve Windows username." >&2
+      return 1
+    fi
+    log_info "Windows User: $windows_user"
+    # Set up Dropbox path
+    #dropbox_path="/mnt/c/Users/${windows_user}/Dropbox (MIT)/"
+    dropbox_path="/mnt/c/Users/${windows_user}/MIT Dropbox/Luis Martinez"
+    if [[ ! -d "$dropbox_path" ]]; then
+
+        log_warning "Warning: Dropbox directory not found at $dropbox_path" >&2
+        # Attempt to find Dropbox directory
+        local potential_path="/mnt/c/Users/${windows_user}/Dropbox (MIT)"
+        if [[ -d "$potential_path" ]]; then
+
+            dropbox_path="$potential_path/"
+            log_info "Found Dropbox at $dropbox_path" >&2
+
+        else
+
+            log_error "Error: Unable to locate Dropbox directory." >&2
+            return 1
+
+        fi
+
+    fi
+
+    # Export variables
+    export WINDOWS_USER="$windows_user"
+    export DROPBOX_PATH="$dropbox_path"
+
+    log_info "Dropbox path setup complete..."
 fi
 
 # Enable programmable completion
