docs(odin): Added the updating of gcc and recompilation

diff --git a/dotfiles/bashrc b/dotfiles/bashrc
--- a/dotfiles/bashrc
+++ b/dotfiles/bashrc
@@ -36,7 +36,7 @@ fi
 setup_completion
 
 # Change to home directory
-cd ~
+cd ~ || echo "Error changing to home directory"
 
 # Additional environment-specific settings
 if [ -x /usr/bin/lesspipe ]; then
@@ -78,6 +78,10 @@ log_info "Use 'count_string <search_string>' to find files with search_string"
 export NVM_DIR="$HOME/.nvm"
 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
 [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+
+# TODO: Have to add this to the configuration when I have time
+export ODIN_ROOT="$HOME/Odin"
+export PATH="$ODIN_ROOT:$PATH"
 
 # >>> conda initialize >>>
 # !! Contents within this block are managed by 'conda init' !!
